version: '3.5'

services:
  axon-pg:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data
    expose:
      - '5432'
    ports:
      - '5432:5432'
    networks:
      - axon-test
    volumes:
      - db-data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=magdalena@umsu.de
      - PGADMIN_DEFAULT_PASSWORD=secret"
      - PGADMIN_LISTEN_PORT=80
    ports:
    - '8070:80'
    networks:
      - axon-test
    volumes:
    - pgadmin-data:/var/lib/pgadmin

  axon-server:
    image: axoniq/axonserver
    ports:
      - '8024:8024'
      - '8124:8214'
    networks:
      - axon-test

volumes:
  db-data:
  pgadmin-data:

networks:
  axon-test: