spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: pg
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
    ddl-auto: update
    generate-ddl: true

  liquibase:
    enabled: false

axon:
  serializer:
    general: default
    events: jackson
    messages: jackson

lombok:
  anyConstructor:
    addConstructorProperties: true