spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/axontest
    username: pg
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
      format_sql: true



  liquibase:
    enabled: true

axon:
  serializer:
    general: default
    events: jackson
    messages: jackson

lombok:
  anyConstructor:
    addConstructorProperties: true