spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: pg
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    #generate-ddl: true
