-- generated by PGADMIN
--------------------------

-- Database: postgres

-- DROP DATABASE postgres;

CREATE DATABASE postgres
    WITH
    OWNER = pg
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

COMMENT ON DATABASE postgres
    IS 'default administrative connection database';