--- generated by PGADMIN
----------------------------

-- Table: public.snapshot_event_entry

-- DROP TABLE public.snapshot_event_entry;

CREATE TABLE public.snapshot_event_entry
(
    aggregate_identifier character varying(255) COLLATE pg_catalog."default" NOT NULL,
    sequence_number bigint NOT NULL,
    type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    event_identifier character varying(255) COLLATE pg_catalog."default" NOT NULL,
    meta_data oid,
    payload oid NOT NULL,
    payload_revision character varying(255) COLLATE pg_catalog."default",
    payload_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    time_stamp character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT snapshot_event_entry_pkey PRIMARY KEY (aggregate_identifier, sequence_number, type),
    CONSTRAINT uk_e1uucjseo68gopmnd0vgdl44h UNIQUE (event_identifier)
)

TABLESPACE pg_default;

ALTER TABLE public.snapshot_event_entry
    OWNER to pg;